# playbooks/lockdown_users.yml

- name: Audit and restrict shell access for non-wheel users
  hosts: local
  connection: local 
  become: yes

  vars_files:
    - ../vault.yml

  vars: 
    ansible_become_password: "{{ become_pass }}"

  tasks:
    - name: Get list of all users with UID ≥ 1000
      command: >
        awk -F: '$3 >= 1000 && $1 != "nobody" { print $1 }' /etc/passwd
      register: user_list

    - name: Restrict shell access for non-wheel users
      user:
        name: "{{ item }}"
        shell: /sbin/nologin
      loop: "{{ user_list.stdout_lines }}"
      when: item != 'ryan'

